### ISSUE TITLE
Help Is appreciated

### ISSUE THREAD

**Issue by hubpf** [Sumu-Ning/AES#14]
Hi,

I'm new to ABAP, appreciate if you can help to pen down what needs to be done to have AES 128 CBC encryption? There are many class file, do I have to create all in SAP? Do you have sample program to do encryption?

Thanks in advance

**Comment by larshp** [comment]
Just install all classes, see http://larshp.github.io/abapGit/guide-online-install.html for how to install.

There are currently no examples, but good idea that we add some, dont know if I'll have the time

**Comment by Sumu-Ning** [comment]
Probably you can check some of the code in the tests?

**Comment by hubpf** [comment]
The test code has error with cl_abap_unit_assert. Does the code (both test code and implementation class) needs certain version of SAP Basis to run?

**Comment by larshp** [comment]
dont think so, most of it is custom code, it should work on 702 and up, though might need a few tweaks for supporting old syntax
