### ISSUE TITLE
Use built-in ABAP types instead of DDIC

### ISSUE THREAD

**Issue by larshp** [Sumu-Ning/AES#17]
Suggest using built-in types instead of referring to DDIC data elements, this will make sure the code works across more systems, following are candiates to be changed

```
DTEL            BOOLE_D
DTEL            CHAR10
DTEL            HEXTYP
DTEL            INT1
DTEL            INT4
```

use `abap_bool`, `type c length 10`, `type x length 1` etc., if needed the types can be defined in a interface

**Comment by WegnerDan** [comment]
I've done the changes and created a [Pull Request](https://github.com/Sumu-Ning/AES/pull/22)

**Comment by WegnerDan** [comment]
I think this can be closed.
