### ISSUE TITLE
AES result is not matching with online tools

### ISSUE THREAD

**Issue by bilencekic** [Sumu-Ning/AES#19]
Hi Everyone,
I did several tests but cannot decrypt same result from https://www.devglan.com/online-tools/aes-encryption-decryption 
It is like decrpting first 2 chars and it is matching. Where is the error ? Is it online tool causing the issue , because they didin't mention what padding they are using. 
I just want a simple test which i can encrypt from ABAP but decrypt from online tool with same key.

**Comment by Sumu-Ning** [comment]
AES is used to encryt/decryt binary data. You also need to consider the encoding of the text, which defines how text is converted from/to binary.

Another thing to pay attention to is the case of ecrypted data, if you are using Base 64

**Comment by bilencekic** [comment]
Ok here is how i tested;
`my key is as plain string  = 1231231231231312`
as HEX `KEY = 31323331323331323331323331333132 ` ( from https://codebeautify.org/string-hex-converter )
`plaintext as string = bilen`
as HEX `plaintext   = '62696C656E'.`

```
   zcl_aes_utility=>encrypt_xstring(
      EXPORTING
        i_key                   = key
        i_data                  = plaintext
        mode  = zcl_aes_utility=>mc_encryption_mode_ecb.
      IMPORTING
        e_data                  = test ).

```

result is coming as 
51A920E8937AD58B754A37F9245FD408

but both here https://encode-decode.com/aes-128-cbc-encrypt-online/    (This one using BASE64)
and here
https://www.devglan.com/online-tools/aes-encryption-decryption
i can't generate same result. 

second link giving "Given final block not properly padded. Such issues can arise if a bad key is used during decryption." error during decrypt. I afraid our paddins are different. i tried PKCS_7 but first 2 char is matching, maybe it is PKCS_5 but method doesn't work with PKCS_5.

I just need to confirm any decrypter can decrypt same result.

**Comment by Sumu-Ning** [comment]
I was able to decryt at http://extranet.cryptomathic.com/aescalc/index?key=31323331323331323331323331333132&iv=00000000000000000000000000000000&input=51A920E8937AD58B754A37F9245FD408&mode=ecb&action=Decrypt&output=

**Comment by bilencekic** [comment]
thanks a lot Mr. Who saved my sleepless nights :D  i think leading zeros fault me. i tested above page as well last time. That proof is enough for me.

**Comment by Sumu-Ning** [comment]
You are welcome, hope this lib is helpful :)
I am going to resolve this issue.
