### ISSUE TITLE
Working Example

### ISSUE THREAD

**Issue by JayKidd81** [Sumu-Ning/AES#20]
Hi, are there any quick ABAP usage examples with this library anywhere? Am keen to give it a try, but wondering where to start... Thanks :)

**Comment by Sumu-Ning** [comment]
Check these unit tests.
https://github.com/Sumu-Ning/AES/blob/master/src/zcl_aes_utility_test.clas.abap

**Comment by JayKidd81** [comment]
Fantastic! :)
