### ISSUE TITLE
Encryption Issue

### ISSUE THREAD

**Issue by sharchandran** [Sumu-Ning/AES#23]
Hi,
I find this code really useful but am struggling to understand where I am going wrong.
I am trying to encrypt with the following details

PKCS5 PAdding.
Cipherkey - 5545427A64334A6B49314E555255564D

I have written code as follows

```
`CALL METHOD zcl_aes_utility=>encrypt_xstring
    EXPORTING
      i_key              = lv_cipherkey
      i_data             = lv_plaintext
*      i_initialization_vector = i_iv
      i_padding_standard = zcl_aes_utility=>mc_padding_standard_pkcs_5
      i_encryption_mode  = zcl_aes_utility=>mc_encryption_mode_ecb
    IMPORTING
      e_data             = lv_ciphertext.`

  CALL FUNCTION 'SCMS_BASE64_ENCODE_STR'
    EXPORTING
      input  = lv_ciphertext
    IMPORTING
      output = lv_encrypted.
```

My plain text is '7B227472616E73616374696F6E4944223A22333039323230313031353739313739343330393730222C22737461747573223A2253756363657373222C227061796D656E744279223A225341505F46554E4331222C22636F6E74726163744E6F223A2247454D432D353131363837373330393232373530222C2267656D496E766F6963654E6F223A2247454D2D3634303139222C22696E766F6963654E6F223A223736746768222C2262696C6C4E6F223A223531313638373733303932323735302D334231222C2262696C6C416D6F756E7450616964223A22373330302E3030222C227472616E73616374696F6E44617465223A22323032302D30312D3136222C226465647563746564416D6F756E74223A22302E303020222C22646564756374696F6E54797065223A22222C2262616E6B4E616D65223A224943494349222C226368657175654E756D626572223A22222C2262616E6B5472616E73616374696F6E4E6F223A22313233343332222C2264656D616E6444726166744E6F223A22222C2273616E6374696F6E4E6F223A22222C2273616E6374696F6E44617465223A22227D'

However, when i get the encoded string, it shows as  below
IUEgq2A30lHwd/tf97TBvuiYKKPj5XjmGwLru5ueFBqdAkZm7M7Di0poHr1FObd2MqEcR/GJvPrcF8hw3rpFQq0SV9tdXP1wctG4s5uf0tppraJHXSI1Vluq/FHhdTHVvxvseg4bQ1671DYIW5tFJ0HCRpm79T8d9XAycgqmb6E4US7v5NP5+420NPIwpQGWDqUV9e8/kdzAhUtTjXZmY8HRS7T5WUgL2pkc6zWbFGKoKrJ9M/TP0IF4puI0oBrFUzmi4ipP74gSo4K+1NvwUhK9pgWXXLggvOyCj62Xu7Gz8r177mR2rMLUQVgI5RmM+yO3lAFUeFyPw8plWo74aTdkdejtBx7VeLlrvi1pXD+m6X7/uasr7AgfRaIlY9sHxqvId11v5zURY7pEVWEF6oODp1bh8o3SKpHhX74KUONJkmEVeVXvuB+QHggJnWNFVzPCg9AOOH8F9BhgY+L5b5gyUnsxrEuioSpamY7WXarQYey8qK+039R+JmZUUW1OwWecPJBCp5gtyIDuiM5FK1IlL7vQaKyv/IHSrCLM+c/iS2Gm2XCuwD1r4Hr/U4Bo

And when i use online tools like https://www.devglan.com/online-tools/aes-encryption-decryption, i get
IUEgq2A30lHwd/tf97TBvuiYKKPj5XjmGwLru5ueFBqdAkZm7M7Di0poHr1FObd2MqEcR/GJvPrcF8hw3rpFQq0SV9tdXP1wctG4s5uf0tppraJHXSI1Vluq/FHhdTHVvxvseg4bQ1671DYIW5tFJ0HCRpm79T8d9XAycgqmb6E4US7v5NP5+420NPIwpQGWDqUV9e8/kdzAhUtTjXZmY8HRS7T5WUgL2pkc6zWbFGKoKrJ9M/TP0IF4puI0oBrFUzmi4ipP74gSo4K+1NvwUhK9pgWXXLggvOyCj62Xu7Gz8r177mR2rMLUQVgI5RmM+yO3lAFUeFyPw8plWo74aTdkdejtBx7VeLlrvi1pXD+m6X7/uasr7AgfRaIlY9sHxqvId11v5zURY7pEVWEF6oODp1bh8o3SKpHhX74KUONJkmEVeVXvuB+QHggJnWNFVzPCg9AOOH8F9BhgY+L5b5gyUnsxrEuioSpamY7WXarQYey8qK+039R+JmZUUW1OwWecPJBCp5gtyIDuiM5FK1IlL7vQaKyv/IHSrCLM+c/6S/NxlgIM1Q1HZM4XlL0W

If you see, the encoded result is same except for the last 21 characters. I do not know how to the the last 21 characters to match the result from devglan site.

Perhaps something wrong with padding which I am unable to identify. I've been thinking about this in my sleep lol.

Before calling the encrypt, i do the following
```
`  CALL FUNCTION 'SCMS_STRING_TO_XSTRING'
    EXPORTING
      text     = lv_key
      encoding = '4110'
    IMPORTING
      buffer   = lv_cipherkey
    EXCEPTIONS
      failed   = 1
      OTHERS   = 2.
  IF sy-subrc <> 0.
*    gv_er_msg = 'Error while Binary conversion of key'(010).
*    RAISE EXCEPTION TYPE cx_alert_cat_exists.
  ENDIF.`

```
```
` CALL FUNCTION 'SCMS_STRING_TO_XSTRING'
    EXPORTING
      text   = lv_paydata
      encoding = '4110'
    IMPORTING
      buffer = lv_plaintext
    EXCEPTIONS
      failed = 1
      OTHERS = 2.
  IF sy-subrc <> 0.
*    gv_er_msg = 'Error while Binary conversion of key'(010).
*    RAISE EXCEPTION TYPE cx_alert_cat_exists.
  ENDIF.`
```

Can you please guide me as to what I might be missing?

Thank you.
S

**Comment by Sumu-Ning** [comment]
I think the problem is padding, I think you should using PKCS7 padding.  
PKCS5 is using 8-byte block for padding, and in my opinion, it is not compatible with AES, since AES is using 16-byte block. 

Your input is 419 bytes, which is 26 blocks + 3 bytes.  
If using PKCS5, it will pad 5 bytes with '05'. (I don't remember what is added after this, but AES does need the whole input to be 16-byte blocks)
If using PKCS7, it will pad 13 bytes with '0D'.

The output you got ending with 'lL0W' is actually from PKCS7 padding, which is your input plus 13 '0D's.

Hope this helps.

BTW, don't use ECB, it creates the identical output blocks for repeated identical input blocks.

**Comment by sharchandran** [comment]
Dear @Sumu-Ning 
Thanks for your quick response. I tried the same logic by just changing from PCKS5 to PKCS7. 
I get the same result as below

IUEgq2A30lHwd/tf97TBvuiYKKPj5XjmGwLru5ueFBqdAkZm7M7Di0poHr1FObd2MqEcR/GJvPrcF8hw3rpFQq0SV9tdXP1wctG4s5uf0tppraJHXSI1Vluq/FHhdTHVvxvseg4bQ1671DYIW5tFJ0HCRpm79T8d9XAycgqmb6E4US7v5NP5+420NPIwpQGWDqUV9e8/kdzAhUtTjXZmY8HRS7T5WUgL2pkc6zWbFGKoKrJ9M/TP0IF4puI0oBrFUzmi4ipP74gSo4K+1NvwUhK9pgWXXLggvOyCj62Xu7Gz8r177mR2rMLUQVgI5RmM+yO3lAFUeFyPw8plWo74aTdkdejtBx7VeLlrvi1pXD+m6X7/uasr7AgfRaIlY9sHxqvId11v5zURY7pEVWEF6oODp1bh8o3SKpHhX74KUONJkmEVeVXvuB+QHggJnWNFVzPCg9AOOH8F9BhgY+L5b5gyUnsxrEuioSpamY7WXarQYey8qK+039R+JmZUUW1OwWecPJBCp5gtyIDuiM5FK1IlL7vQaKyv/IHSrCLM+c/iS2Gm2XCuwD1r4Hr/U4Bo
```

  CALL METHOD zcl_aes_utility=>encrypt_xstring
    EXPORTING
      i_key              = lv_cipherkey
      i_data             = lv_plaintext
      i_initialization_vector = i_iv
      i_padding_standard = zcl_aes_utility=>mc_padding_standard_pkcs_7
      i_encryption_mode  = zcl_aes_utility=>mc_encryption_mode_ecb
    IMPORTING
      e_data             = lv_ciphertext.
```

The last characters again do not have 'IL0W'.

I then tried to change the ECB mode but it gave me an unexpected result like below
IUEgq2A30lHwd/tf97TBvnFui0TB4XGNc50/dL0nSDa3uOTJAR8fsYCOhUKYWeBkotZ6i/+FLFAohatOzNEhNTkuhACyLZrgxlxtpCi3TuNh+fE+fCpZj5Pk4s81tYy/G6o+C1WtZejuM+QYNBq33TJOiKHdO14QY2+3DFQWzCWdwyiRF/WpCfVtDVruZD02NfVCcYEi2dUCDjecWf6Ng0pOJYCLTZUXSTnSHPSe1aezrKkcun77rJ7jJ/Ock7L8sSAWiZw9ExlXpC+Q+VXv4niRIbRMqOg/ro0AUFVQlQaxL0HEegpSzY6rr5Lj8KfqmAmXdb84Bd//+UF8Kgj5iWR+SmQh3KgjFXIzx5aiE3hV5Z0wwpKoCKXSchKe30GedClxRtE1M/I4N0ydHIKWe+jD1bGhFz07N1FOACLTwph+BLZgldO/5kZlmD7t+aRKl08sdtVlBKQBxWsCiwCokbHhwY9SkDVExAu3uMUi1Xqru8zt03H9TXnlnpoxwtGgZ3/S2RRavw7/x9ZO3TJB5FM3BTd6hZ7MaqoPDNFKtGx0K82CWXUQYdVLM9sthGyL

Do i need to logically change the input?

**Comment by Sumu-Ning** [comment]
I decrypted your output ending with "U4Bo", and the decrypted data has the last 13 bytes all "00".

So it looks like padding is not used at all.

I don't have an environment right now, so I could test in person. But I think you can try debugging the problem, and check what data is passed to the actual encryption algorithm after padding.

**Comment by sharchandran** [comment]
Dear @Sumu-Ning 
Thank you very much. As you said, while i debugged I noticed that the padding logic was not really doing anything. So i wrote some logic to append '0D' based on what you mentioned above and it's working perfectly. 
Thanks very much for your suggestions.
Please do feel free to close this topic.

Thanks & Regards,
Sharat Chandran

**Comment by Sumu-Ning** [comment]
Appending padding characters should be the responsibility of the padding logic in the code. Not sure why it is not working, it would be great if you can help deep dive on it.  

However, for your own case, please don't just append '0D'. 

According to PKCS7, 
If the input data is missing 1 byte to make a 16-byte block, it will append 1 '01'
If the input data is missing 2 bytes to make a 16-byte block, it will append 2 '02's, 
and so on.
For your case, the input is missing 13 bytes to make a 16-byte block, so it needs to append 13 '0D's

So that after decryption, you can know how many bytes at the end is the padding.

**Comment by sharchandran** [comment]
Dear Sumu-Ning, That is what I have done. Please find below the logic that I have written. 
Do let me know if it can be improved or if there is a better way.

```
DATA:
  lv_length_of_last_line TYPE int4,
  lv_iter TYPE int4,
  lv_iter_count TYPE int4,
  lv_pad_pkcs7 TYPE xstring,
  lx_data TYPE xstring.

    lv_length_of_last_line =  xstrlen( i_data ).
" Get iteration count number
    lv_iter = I_BLOCK_LENGTH_IN_BYTE - lv_length_of_last_line.
    lv_pad_pkcs7 = '0D'.
    lv_iter_count = 0.

    lx_data = i_data.

    WHILE lv_iter_count < lv_iter.
      CONCATENATE lx_data lv_pad_pkcs7 INTO lx_data IN BYTE MODE.
      lv_iter_count = lv_iter_count + 1.
    ENDWHILE.

    e_data = lx_data.
```

**Comment by Sumu-Ning** [comment]
@larshp Have you ever met the case that padding is not working after the latest commit?

**Comment by Sumu-Ning** [comment]
lv_pad_pkcs7 needs to be a variable, instead of always '0D'.

the logic of PKCS7 is here:
https://github.com/Sumu-Ning/AES/blob/master/src/zcl_padding_utility_pkcs_7.clas.abap
