### ISSUE TITLE
AES  盐值 解密。怎么调用呢？

### ISSUE THREAD

**Issue by janewar** [Sumu-Ning/AES#25]
AES  盐值 解密。怎么调用呢？
DECRYPT_IV 
https://blogs.sap.com/2019/08/26/aes-encryption-in-abap/
https://www.soinside.com/question/kXANQ2vSqP4xbcyBXD2sqR

**Comment by Sumu-Ning** [comment]
What do you mean by Salt? Initial Vector? If initial vector, it is only applicable to some of the encryption mode.

你说的盐值具体指什么？是初始向量吗？如果是初始向量的话，它只适用于一些而非所有加密模式。
