### ISSUE TITLE
Last bytes of AES encryption result is not matching with online tools

### ISSUE THREAD

**Issue by venumaripi** [Sumu-Ning/AES#26]
my string: 
{"transactionID":"175738861574757193070","status":"SUCCESS","paymentBy":"INTERNET BANKING","contractNo":"GEMC-11687717573886","gemInvoiceNo":"GEM-61550","invoiceNo":"3131","billNo":"511687717573886-1B1","billAmountPaid":"391108.00","transactionDate":"2020-03-02","deductedAmount":"0","deductionType":"LD/TDS","bankName":"SBI","chequeNumber":"","bankTransactionNo":"SBIUATTEST1234","demandDraftNo":"","sanctionNo":"","sanctionDate":""}

my key: qcNv4GRqj40WdqhY

iam using ECB128/PKCS5PADDING

 zcl_aes_utility=>encrypt_xstring(
   exporting
     i_key                     = i_key_xstring
     i_data                    = i_xstring
     i_padding_standard = ZCL_PADDING_UTILITY_PKCS_5=>MC_PADDING_STANDARD_PKCS_5
     i_encryption_mode         = zcl_aes_utility=>mc_encryption_mode_ecb   "mode
   importing
     e_data                    = lv_message   ).

iam getting:
HmS6lVtVWBJRkPozvNUFU4uF7/ihCQT64oE3TaMF2pqGW4MK1Kr+bq2IaxVOVGCwe72sotxVC+H88qeAQXnUpCdVlUFUsWg7d73vqnw7IbUhSJnBQ+7mfhNz2FdSuxGfyAIzlxMJBxSP0Lz1gF5m98Xd1VdUpivc1GvxacrLqRWmm+TIr63nm2WzSiR3WE8P2Oy+gK/VIrInDaliVEnPbsu0Tfpd1+0RX85AiAcRsh4xpUEpM1f2e0lVCfDcrd3ooy5CEjHGMLUjImIix3rMCwyv4dBV1YDGPWiUd4X+Nedd+lh1+ROk5gQtlw2juCipxhXFFgIA0sfHuHJRACm53oJWTm45S8rbBFs6ygDaDK0lMe/DfAT1lvhwIVG69X5S6t8EVpL1RTmmFINX4b+zsbDnlV1dfBfUXsnX+wjDWgEo1Tk1TTKoo6tRHunAQs8ZmK31lx4oxl5SD5QQ2uwKg7zu38beXTUAYTXDim5qyRHZ536VnN7iXP30FGpHaUIMHvxIb7G5DnBURGIafOYotaKQ8W8wUo2fYOd3GMFyHja1iaLVavr/BttVTOrvqDKlFw7tLK//nTTqBqGNA9nTNg==

whereas online tool at [https://www.devglan.com/online-tools/aes-encryption-decryption] is showing:
HmS6lVtVWBJRkPozvNUFU4uF7/ihCQT64oE3TaMF2pqGW4MK1Kr+bq2IaxVOVGCwe72sotxVC+H88qeAQXnUpCdVlUFUsWg7d73vqnw7IbUhSJnBQ+7mfhNz2FdSuxGfyAIzlxMJBxSP0Lz1gF5m98Xd1VdUpivc1GvxacrLqRWmm+TIr63nm2WzSiR3WE8P2Oy+gK/VIrInDaliVEnPbsu0Tfpd1+0RX85AiAcRsh4xpUEpM1f2e0lVCfDcrd3ooy5CEjHGMLUjImIix3rMCwyv4dBV1YDGPWiUd4X+Nedd+lh1+ROk5gQtlw2juCipxhXFFgIA0sfHuHJRACm53oJWTm45S8rbBFs6ygDaDK0lMe/DfAT1lvhwIVG69X5S6t8EVpL1RTmmFINX4b+zsbDnlV1dfBfUXsnX+wjDWgEo1Tk1TTKoo6tRHunAQs8ZmK31lx4oxl5SD5QQ2uwKg7zu38beXTUAYTXDim5qyRHZ536VnN7iXP30FGpHaUIMHvxIb7G5DnBURGIafOYotaKQ8W8wUo2fYOd3GMFyHja1iaLVavr/BttVTOrvqDKlKfxb5PoFsX2FsS1vGmTUVQ==

we need to send an encrypted text to a destination, where message will be decrypted, processed and response will be sent back.
encrypted message through zcl_aes_utility was showing an error at receiver side.
encrypted message through online tool has worked properly as expected.

difference between above 2 encrypted messages is last 24 characters.
Please let me know if iam missing anything during encryption

**Comment by Sumu-Ning** [comment]
If you are using ECB and the last block differs, it is almost certain the issue is from padding.
I would suggest trying to use PKCS7 padding, since PKCS5 does not really make sense with AES.

We had some similar discussions before:
https://github.com/Sumu-Ning/AES/issues/4
https://github.com/Sumu-Ning/AES/issues/3
https://github.com/Sumu-Ning/AES/issues/23

Also, it is probably not good to use ECB:
https://en.wikipedia.org/wiki/Block_cipher_mode_of_operation

**Comment by venumaripi** [comment]
Dear Sumu-Ning,
Thank you very much for your prompt response.
changing to PKCS7 has resolved the issue.
Your library is of great help.
