### ISSUE TITLE
Some "garbage" as suffix left after decrypting via AES-CBC

### ISSUE THREAD

**Issue by haimat** [Sumu-Ning/AES#3]
Hi, thanks for adding the CBC support to your library, now I can successfully decrypt AES-encrypted strings (in base64) coming from OpenSSL. There seems to be a bug though somewhere. I do the following steps:

First, I get the key and init. vector for the password from OpenSSL:

```
openssl aes-256-cbc -nosalt -P -pass pass:unserGeheimesPasswort
```

Then I encrypt a string using that same password:

```
echo geheime_Kundendaten | openssl enc -aes-256-cbc -a -nosalt -pass pass:unserGeheimesPasswort
```

In ABAP I decode that encrypted base64-encoded string:

```
CALL FUNCTION 'SCMS_BASE64_DECODE_STR'
  EXPORTING
    input    = p_data  "base64-encoded, encrypted AES string: geheime_Kundendaten
    unescape = 'X'
  IMPORTING
    output   = lv_x_data.
```

Then I decrypt that string via your class:

```
CALL METHOD lr_aes_util->decrypt_xstring(
  EXPORTING
    i_data                  = lv_x_data
    i_key                   = lv_x_key
    i_initialization_vector = lv_x_iv
    i_encryption_mode       = 'CBC'
  IMPORTING
    e_data                  = lv_x_result ).
```

That method call returns the correctly decrypted string, which I have encrypted via OpenSSL before. However, there are some additional bytes as suffix. In the ABAP debugger the value of `lv_x_result` is

```
67656865696D655F4B756E64656E646174656E200D0A0A0A0A0A0A0A0A0A0A0A
```

which, after converting the xstring to binary via `SCMS_XSTRING_TO_BINARY` and from binary to string via `SCMS_BINARY_TO_STRING` results in

```
geheime_Kundendaten ############
```

So the first part is correct, but these trailing `############` should not be there. When I remove all the `0D0A` bytes (Carriage Return / Line Feed) from the xstring, then the result is correct.

Now, is this a bug in your code, or do I need an additional step to decrypt AES-CBC correctly?

**Comment by Sumu-Ning** [comment]
I guess it is from openssl, but I cannot prove it right now.

From openssl side, when it tries to encrypt using AES, it has to fill the binary data to multiples of 128 bit. The binary representation of the plaintext might not necessarily be multiple of 128 bit, and the extra data should be the padding

**Comment by Sumu-Ning** [comment]
Here is something, and it is saying that openssl aes is using pkcs#7 padding

http://crypto.stackexchange.com/questions/12621/why-does-openssl-append-extra-bytes-when-encrypting-with-aes-128-ecb

Padding 0A means you have 10 (0A in hex) bytes attached.
The extra 0D0A might be the extra "New Line" added by echo, I am guessing you are using a windows machine?

**Comment by haimat** [comment]
Ohh yes, that makes sense, thanks a lot. My solution now is to remove all trailing bytes <= 20, which works quite well. Thanks!

**Comment by Sumu-Ning** [comment]
Great. If you want to make it more accurate and works all the time, just remove the number of trailing bytes by the value of the last byte.
