### ISSUE TITLE
abapGit repository format

### ISSUE THREAD

**Issue by larshp** [Sumu-Ning/AES#5]
Hi,
I am working on implementing OpenPGP in ABAP

https://github.com/larshp/abapPGP
https://tools.ietf.org/html/rfc4880

And will eventually need AES encryption, and I have found your nice AES library :+1: 

In order to make it easier to install, have you considered using [abapGit](https://github.com/larshp/abapGit), and will you accept a pull request which changes the format to abapGit format? 

You can take a look at https://github.com/larshp/abapPGP for how abap code in abapGit format looks like in a git repository.

**Comment by Sumu-Ning** [comment]
Thank you for your proposal!
Currently I don't have ABAP environment any more, and I invited you as collaborator.
I accepted your pull request, and hopefully you can keep maintain this library as needed in the future.

Thank you!

**Comment by larshp** [comment]
cool, thanks :smile: 

It looks like I need some PKCS1 padding(https://tools.ietf.org/html/rfc4880#section-13.1), and a special OpenPGP CFB mode(https://tools.ietf.org/html/rfc4880#section-13.9), which I might implement

closing
